server:
  port: 8082

spring:
  application:
    name: ORDER-SERVICE
eureka:
  instance:
    hostname: localhost

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
